apiVersion: v1
kind: ConfigMap
metadata:
  name: init-config
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  init-config.json: >-
    {
      "secret_shares": 5,
      "secret_threshold": 3,
      "stored_shares": 5,
      "recovery_shares": 3,
      "recovery_threshold": 3
    }