apiVersion: v1
kind: ConfigMap
metadata:
  name: keys-policy
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  keys-policy.json: >-
    {
      "policy": "path \"transit/*\" {\n capabilities = [ \"read\", \"list\", \"create\", \"update\" ]\n}"}"
    }