apiVersion: v1
kind: ConfigMap
metadata:
  name: main-key
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  main-key.json: >-
    {
      "convergent_encryption": true,
      "derived": true
    }