apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-regulation-management-encryption-key
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  registry-regulation-management-encryption-key.json: >-
    {
      "convergent_encryption": false,
      "derived": false,
      "auto_rotate_period": 0
    }