apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-for-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - '*'
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch 