apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-engine
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  secret-engine.json: >-
    {
      "type": "kv-v2",
      "config": {
        "force_no_cache": true
      }
    }